2023/12/16 00:14:21 - dataset - [ERROR] - Exception happens at the `25369`th instance.
